### PR TITLE
example: simplify major version updates

### PR DESCRIPTION
**Pull request by AaronFriel**
This commit is an example of a change to be rolled out with ci-mgmt.

Providers are free to modify their major version without requiring many code changes beyond changing the code in `./provider`:

1. disabling examples tests (can be done with PR changing provider code)
2. ci-mgmt change to bump the major version
3. ci-mgmt PR against repo updating major version in CI files
4. re-enabling examples

To accomplish this, files managed via ci-mgmt no longer require using the major version number of the provider in any scripts. This major version appears in:

* Makefile: no longer required as go commands now use paths to build and modifying ldflags version argument
* goreleaser: no longer required by modifying version ldflags argument
* GitHub Actions: no longer required as an environment variable

A change to pulumi/pkg ProgramTest is needed to modify `Dependencies` to remove the need to disable and re-enable examples:
- https://github.com/pulumi/pulumi/pull/12004

### CODE REVIEW

**Review by guineveresaenger — COMMENTED** [review]
So basically, we would have a versionless version package? 😂 

I love seeing this example, but have we tried this out somewhere?

**Comment by AaronFriel** [comment]
@guineveresaenger this PR is the trial run: provider build, schema and SDK generation, examples are all green. 

And to validate that the version is getting in there, tfgen panics if `version.Version` is the empty string, console output during `make provider` shows the correct version number.

**Review by iwahbe — APPROVED** [review]
This looks like a good prototype. I wasn't sure we could just remove the version prefixes where we describe the module, such as specifying linker flags. Given that tests go green, I'm comfortable merging. 

I'll wait on master to go green before rolling out the change to other providers, since that invokes the goreleaser in it's publish step.

**Comment by AaronFriel** [comment]
@iwahbe this commit introduces a go.mod file at provider/pkg/version, making it a separate module fixed at v0 enables the ldflags change.

**Pull request merged**
